[package]
name = "tarthis-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
async-compression = { version = "0.4.12", features = ["all"] }
chrono = "0.4.38"
inquire = "0.7.5"
tar = "0.4.41"
tokio = { version =  "1.39.1", features = ["full"] }
tokio-tar = "0.3.1"
